### ISSUE TITLE
Image Analysis and Preprocessing

### ISSUE THREAD

**Issue by ArchuY** [LSTM-Team/HDSC-Winter-22-Capstone-Project#3]
Code guidelines by Hamoye

https://drive.google.com/file/d/1hC55DKTg6qtI38IQq-U7Ze59AWYI3bNK/view?usp=sharing

**Comment by faryar251** [comment]
@ArchuY @Rubylena Can i get some feedback from you both, so i can do modifications accordingly?

**Comment by Rubylena** [comment]
Make your modifications and PR everything into the production branch, I will be deleting your branch so please do well to fork and clone the repository.
Thanks

**Comment by ArchuY** [comment]
> 

Just go for OpenCV part, try to do image smoothing, noise removing on images
